- name: add ssh key for Rudolph
  authorized_key:
    user: rudolph
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICd6+L2xbxKqhhF65TWUKQ6w5GWEq8SFJ/l2gq4woxJB ansible"


- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
